version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  product-service:
#    build:
#      context: ./product-service
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productdb
#      SPRING_DATASOURCE_USERNAME: product_user
#      SPRING_DATASOURCE_PASSWORD: product_pass
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
#      # Adjust issuer/eureka if needed
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/microservices-realm
#      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka
#    ports:
#      - "8081:8081"

volumes:
  pgdata:

